services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=5s
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3001:3000"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

  webapp:
    image: nginx:latest  # Image nginx standard
    container_name: webapp
    volumes:
      - ./nginx-vts.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-logs:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - monitoring
      
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest  # Image officielle corrigée
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://webapp/stub_status
    ports:
      - "9113:9113"
    networks:
      - monitoring
    depends_on:
      - webapp
  


  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6:/scripts
    networks:
      - monitoring

  # Modification à apporter à votre compose.yml
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./nginx-logs:/var/log/nginx:ro
    ports:
      - "9273:9273"
    networks:
      - monitoring
    depends_on:
      - webapp
      - prometheus

  nginx-log-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:latest
    container_name: nginx-log-exporter
    volumes:
      - ./nginx-exporter-config.yml:/etc/nginx-log-exporter/config.yml
      - ./nginx-logs:/var/log/nginx
    ports:
      - "4040:4040"
    networks:
      - monitoring
    depends_on:
      - webapp

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: