services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=5s
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3001:3000"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

  webapp:
    image: wodby/nginx:latest  # Image avec VTS préinstallé
    # Alternativement : FROM nginx:1.21 puis compilez avec le module VTS
    container_name: webapp
    volumes:
      - ./nginx-vts.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - monitoring
      
  vts-exporter:
    image: sophos/nginx-vts-exporter:latest
    container_name: vts-exporter
    environment:
      - NGINX_STATUS=http://webapp/status/format/json
    ports:
      - "9913:9913"
    networks:
      - monitoring
    depends_on:
      - webapp

  nginx-plus-exporter:
    image: nginxinc/nginx-prometheus-exporter:latest
    command:
      - -nginx.plus
      - -nginx.scrape-uri=http://webapp/api
    ports:
      - "9113:9113"
    networks:
      - monitoring

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6:/scripts
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: